"""Evaluation: metrics, figures, and latency benchmark.

Produces (all regenerated by ``make eval``):

  results/tables/
    test_metrics.tex              R², RMSE per (model, target) on test split
    heldout_metrics.tex           same on the RAE2822 unseen-geometry slice
    latency.tex                   mean ± std single-sample inference time (ms)

  results/figures/eval/
    parity_<model>.png            predicted vs true scatter (both targets)
    residuals_mach_<model>.png    RMSE per Mach bin
    cm_vs_alpha.png               Cm(α) overlay: CFD truth + all models
    feature_importance.png        RF and XGBoost normalized importances

All public functions accept raw (unscaled) y_true / y_pred arrays in the
original coefficient space (after inverse-transforming the z-scored preds).
"""
from __future__ import annotations

import time
from pathlib import Path
from typing import Any, Dict, List, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from sklearn.metrics import mean_squared_error, r2_score

from src import viz  # noqa: F401 — applies shared rcParams
from src.config import FIGURES_DIR, TABLES_DIR, TARGET_COLS
from src.models.dnn import AeroMLP

EVAL_FIG_DIR = FIGURES_DIR / "eval"


def _ensure(path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    return path


# ─── Generic predict helper ──────────────────────────────────────────────────
def predict(model: Any, X: np.ndarray) -> np.ndarray:
    """Return (n, 2) predictions regardless of model type."""
    if isinstance(model, AeroMLP):
        model.eval()
        with torch.no_grad():
            out = model(torch.from_numpy(X).float()).numpy()
        return out
    return model.predict(X)   # sklearn / XGBoostMultiOutput


# ─── Scalar metrics ──────────────────────────────────────────────────────────
def compute_metrics(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    target_cols: List[str] = TARGET_COLS,
) -> Dict[str, Dict[str, float]]:
    """Return per-target RMSE and R² in the original (unscaled) space."""
    result = {}
    for i, t in enumerate(target_cols):
        rmse = float(np.sqrt(mean_squared_error(y_true[:, i], y_pred[:, i])))
        r2   = float(r2_score(y_true[:, i], y_pred[:, i]))
        result[t] = {"rmse": rmse, "r2": r2}
    return result


# ─── LaTeX table helpers ─────────────────────────────────────────────────────
def _metrics_to_df(metrics_per_model: Dict[str, Dict]) -> pd.DataFrame:
    rows = []
    for model_name, targets in metrics_per_model.items():
        for target, vals in targets.items():
            rows.append({
                "Model":  model_name,
                "Target": f"${target}$",
                "RMSE":   f"{vals['rmse']:.4f}",
                "R²":     f"{vals['r2']:.4f}",
            })
    return pd.DataFrame(rows)


def save_metrics_table(
    metrics_per_model: Dict[str, Dict],
    path: Path,
) -> Path:
    """Write a LaTeX booktabs table (Model | Target | RMSE | R²) to path."""
    _ensure(path)
    df = _metrics_to_df(metrics_per_model)
    lines = [
        r"\begin{tabular}{llrr}", r"\toprule",
        "Model & Target & RMSE & $R^2$ \\\\ \\midrule",
    ]
    prev_model = None
    for _, row in df.iterrows():
        model_cell = row["Model"] if row["Model"] != prev_model else ""
        prev_model = row["Model"]
        lines.append(f'{model_cell} & {row["Target"]} & {row["RMSE"]} & {row["R²"]} \\\\')
    lines += [r"\bottomrule", r"\end{tabular}"]
    path.write_text("\n".join(lines))
    return path


# ─── Parity plots ────────────────────────────────────────────────────────────
def plot_parity(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    model_name: str,
    save_path: Path | None = None,
    target_cols: List[str] = TARGET_COLS,
) -> Path:
    """Scatter of predicted vs CFD truth for both Cl and Cm."""
    if save_path is None:
        save_path = EVAL_FIG_DIR / f"parity_{model_name.lower().replace(' ', '_')}.png"

    fig, axes = plt.subplots(1, 2, figsize=(10, 4.5))
    for ax, i, t in zip(axes, range(2), target_cols):
        lo = min(y_true[:, i].min(), y_pred[:, i].min())
        hi = max(y_true[:, i].max(), y_pred[:, i].max())
        ax.scatter(y_true[:, i], y_pred[:, i], s=8, alpha=0.5, edgecolors="none")
        ax.plot([lo, hi], [lo, hi], "k--", lw=0.8)
        rmse = np.sqrt(mean_squared_error(y_true[:, i], y_pred[:, i]))
        r2   = r2_score(y_true[:, i], y_pred[:, i])
        ax.set_xlabel(f"CFD ${t}$")
        ax.set_ylabel(f"Predicted ${t}$")
        ax.set_title(f"{model_name} — ${t}$\nRMSE={rmse:.4f}, $R^2$={r2:.4f}")

    fig.suptitle(f"Parity plot: {model_name}", y=1.01)
    fig.tight_layout()
    fig.savefig(_ensure(save_path))
    plt.close(fig)
    return save_path


# ─── Residuals by Mach bin ────────────────────────────────────────────────────
def plot_residuals_by_mach(
    y_true:     np.ndarray,
    y_pred:     np.ndarray,
    mach_vals:  np.ndarray,
    model_name: str,
    save_path:  Path | None = None,
    target_cols: List[str] = TARGET_COLS,
) -> Path:
    """Bar chart of RMSE per Mach number for each target."""
    if save_path is None:
        save_path = EVAL_FIG_DIR / f"residuals_mach_{model_name.lower().replace(' ', '_')}.png"

    machs = sorted(np.unique(mach_vals))
    fig, axes = plt.subplots(1, 2, figsize=(10, 4))
    for ax, i, t in zip(axes, range(2), target_cols):
        rmses = [
            float(np.sqrt(mean_squared_error(
                y_true[mach_vals == m, i],
                y_pred[mach_vals == m, i],
            )))
            for m in machs
        ]
        ax.bar([f"{m:.2f}" for m in machs], rmses, color="#4c78a8", alpha=0.75)
        ax.set_xlabel(r"$M_\infty$")
        ax.set_ylabel(f"RMSE (${t}$)")
        ax.set_title(f"${t}$ RMSE by Mach — {model_name}")

    fig.tight_layout()
    fig.savefig(_ensure(save_path))
    plt.close(fig)
    return save_path


# ─── Cm vs alpha overlay ────────────────────────────────────────────────────
def plot_cm_vs_alpha(
    predictions: Dict[str, np.ndarray],
    df_split:    pd.DataFrame,
    mach:        float = 0.80,
    airfoil:     str   = "RAE2822",
    save_path:   Path | None = None,
) -> Path:
    """Cm(α) overlay: CFD ground truth and all model predictions.

    Filters df_split to the given airfoil + Mach, then plots Cm vs α
    for each model alongside the CFD truth. Used to sanity-check that
    the shock-induced nonlinearity at M=0.8 is captured.
    """
    if save_path is None:
        save_path = EVAL_FIG_DIR / f"cm_vs_alpha_M{mach:.2f}_{airfoil}.png"

    mask = (df_split["airfoil"] == airfoil) & (np.abs(df_split["Mach"] - mach) < 1e-6)
    sub  = df_split[mask].sort_values("alpha")

    if len(sub) == 0:
        return save_path   # skip if slice not available (e.g. on test split for RAE2822)

    row_idx = sub.index.tolist()
    alpha   = sub["alpha"].values
    cm_cfd  = sub["Cm"].values

    fig, ax = plt.subplots(figsize=(7, 4.5))
    ax.plot(alpha, cm_cfd, "k-o", ms=4, lw=1.5, label="CFD (truth)")

    colors = plt.cm.tab10.colors
    for (name, preds), color in zip(predictions.items(), colors):
        cm_pred = preds[row_idx, 1]   # column 1 = Cm
        ax.plot(alpha, cm_pred, "--", color=color, lw=1.2, label=name)

    ax.set_xlabel(r"$\alpha$ (deg)")
    ax.set_ylabel(r"$C_m$")
    ax.set_title(f"{airfoil} at $M={mach}$: $C_m$ vs. $\\alpha$")
    ax.legend(fontsize=8)
    ax.axhline(0, color="k", lw=0.3, alpha=0.4)
    fig.tight_layout()
    fig.savefig(_ensure(save_path))
    plt.close(fig)
    return save_path


# ─── Feature importance ───────────────────────────────────────────────────────
def plot_feature_importance(
    rf_model:    Any,
    xgb_wrapper: Any,
    feature_cols: List[str] | None = None,
    save_path:   Path | None = None,
) -> Path:
    """Normalized feature importances from RF and XGBoost (Cl model only)."""
    from src.config import FEATURE_COLS
    if feature_cols is None:
        feature_cols = FEATURE_COLS
    if save_path is None:
        save_path = EVAL_FIG_DIR / "feature_importance.png"

    rf_imp  = rf_model.feature_importances_
    xgb_imp = xgb_wrapper.models_["Cl"].feature_importances_
    rf_imp  = rf_imp  / rf_imp.max()
    xgb_imp = xgb_imp / xgb_imp.max()

    idx  = np.argsort(rf_imp)[::-1]
    cols = [feature_cols[i] for i in idx]

    fig, axes = plt.subplots(1, 2, figsize=(13, 5), sharey=True)
    for ax, imp, title in zip(
        axes,
        [rf_imp[idx], xgb_imp[idx]],
        ["Random Forest", "XGBoost (Cl)"],
    ):
        ax.barh(range(len(cols)), imp[::-1], color="#4c78a8", alpha=0.75)
        ax.set_yticks(range(len(cols)))
        ax.set_yticklabels(cols[::-1], fontsize=7)
        ax.set_xlabel("Normalized importance")
        ax.set_title(title)

    fig.suptitle("Feature importance (normalized, sorted by RF)", y=1.01)
    fig.tight_layout()
    fig.savefig(_ensure(save_path))
    plt.close(fig)
    return save_path


# ─── Prediction distribution KDE ─────────────────────────────────────────────
def plot_prediction_distributions(
    y_true: np.ndarray,
    preds_per_model: Dict[str, np.ndarray],
    save_path: Path | None = None,
    target_cols: List[str] = TARGET_COLS,
) -> Path:
    """KDE overlay: ground-truth + all 4 model prediction distributions.

    One panel per target (Cl, Cm). Ground truth is a filled area; each model
    is a distinct colour line. Reveals whether a model is biased or has
    narrower/wider spread than CFD — complementary to the parity scatter.
    """
    from scipy.stats import gaussian_kde

    if save_path is None:
        save_path = EVAL_FIG_DIR / "prediction_kde.png"

    model_names = list(preds_per_model.keys())
    colors = ["#e15759", "#4e79a7", "#f28e2b", "#76b7b2"]  # Tableau-ish palette

    fig, axes = plt.subplots(1, 2, figsize=(10, 4))

    for col, t in enumerate(target_cols):
        ax = axes[col]
        vals_gt = y_true[:, col]
        xmin = min(vals_gt.min(), *(preds_per_model[m][:, col].min() for m in model_names))
        xmax = max(vals_gt.max(), *(preds_per_model[m][:, col].max() for m in model_names))
        xs = np.linspace(xmin - 0.05 * (xmax - xmin), xmax + 0.05 * (xmax - xmin), 400)

        # Ground truth — filled
        kde_gt = gaussian_kde(vals_gt)
        ax.fill_between(xs, kde_gt(xs), alpha=0.25, color="grey", label="CFD truth")
        ax.plot(xs, kde_gt(xs), color="grey", lw=1.5)

        # Model predictions — lines only
        for i, name in enumerate(model_names):
            vals_m = preds_per_model[name][:, col]
            kde_m = gaussian_kde(vals_m)
            ax.plot(xs, kde_m(xs), color=colors[i % len(colors)], lw=1.5, label=name)

        ax.set_xlabel(f"$C_{{{t[1]}}}$", fontsize=10)
        ax.set_ylabel("Density", fontsize=10)
        ax.set_title(f"Prediction distribution — ${t}$", fontsize=10)
        ax.legend(fontsize=8)

    fig.suptitle("KDE of predicted vs. CFD ground-truth distributions (test split)", fontsize=10)
    fig.tight_layout()
    fig.savefig(_ensure(save_path), dpi=150, bbox_inches="tight")
    plt.close(fig)
    return save_path


# ─── Combined parity (all models) ────────────────────────────────────────────
def plot_parity_all(
    y_true: np.ndarray,
    preds_per_model: Dict[str, np.ndarray],
    save_path: Path | None = None,
    target_cols: List[str] = TARGET_COLS,
) -> Path:
    """4×2 parity grid — one row per model, Cl and Cm columns."""
    if save_path is None:
        save_path = EVAL_FIG_DIR / "parity_all_models.png"

    model_names = list(preds_per_model.keys())
    n = len(model_names)
    # 2 rows (one per target) × n cols (one per model) — landscape, fits article width
    fig, axes = plt.subplots(2, n, figsize=(4 * n, 7))

    for col, name in enumerate(model_names):
        y_pred = preds_per_model[name]
        for row, t in enumerate(target_cols):
            ax = axes[row, col]
            lo = min(y_true[:, row].min(), y_pred[:, row].min())
            hi = max(y_true[:, row].max(), y_pred[:, row].max())
            ax.scatter(y_true[:, row], y_pred[:, row], s=5, alpha=0.4, edgecolors="none")
            ax.plot([lo, hi], [lo, hi], "k--", lw=0.8)
            rmse = np.sqrt(mean_squared_error(y_true[:, row], y_pred[:, row]))
            r2   = r2_score(y_true[:, row], y_pred[:, row])
            ax.set_xlabel(f"CFD ${t}$", fontsize=8)
            ax.set_ylabel(f"Predicted ${t}$", fontsize=8)
            ax.set_title(f"{name}\nRMSE={rmse:.4f},  $R^2$={r2:.4f}", fontsize=8)
            if row == 0:
                ax.set_title(f"{name}\n$C_l$: RMSE={rmse:.4f}, $R^2$={r2:.4f}", fontsize=8)
            else:
                ax.set_title(f"$C_m$: RMSE={rmse:.4f}, $R^2$={r2:.4f}", fontsize=8)

    axes[0, 0].set_ylabel("Predicted $C_l$", fontsize=8)
    axes[1, 0].set_ylabel("Predicted $C_m$", fontsize=8)
    fig.suptitle("Parity: CFD truth vs. predicted — test split (238 samples)", fontsize=10)
    fig.tight_layout()
    fig.savefig(_ensure(save_path), dpi=150, bbox_inches="tight")
    plt.close(fig)
    return save_path


# ─── Combined residuals by Mach (all models) ─────────────────────────────────
def plot_residuals_mach_all(
    y_true: np.ndarray,
    preds_per_model: Dict[str, np.ndarray],
    mach_vals: np.ndarray,
    save_path: Path | None = None,
    target_cols: List[str] = TARGET_COLS,
) -> Path:
    """4×2 residuals-by-Mach grid — one row per model, Cl and Cm columns."""
    if save_path is None:
        save_path = EVAL_FIG_DIR / "residuals_mach_all_models.png"

    model_names = list(preds_per_model.keys())
    n = len(model_names)
    machs = sorted(np.unique(mach_vals))

    # 2 rows (one per target) × n cols (one per model) — landscape layout
    fig, axes = plt.subplots(2, n, figsize=(4 * n, 6))

    for col, name in enumerate(model_names):
        y_pred = preds_per_model[name]
        for row, t in enumerate(target_cols):
            ax = axes[row, col]
            rmses = [
                float(np.sqrt(mean_squared_error(
                    y_true[mach_vals == m, row],
                    y_pred[mach_vals == m, row],
                )))
                for m in machs
            ]
            ax.bar([f"{m:.2f}" for m in machs], rmses, color="#4c78a8", alpha=0.75)
            ax.set_xlabel(r"$M_\infty$", fontsize=8)
            ax.set_ylabel(f"RMSE (${t}$)", fontsize=8)
            ax.set_title(f"{name} — ${t}$", fontsize=8)

    fig.tight_layout()
    fig.savefig(_ensure(save_path), dpi=150, bbox_inches="tight")
    plt.close(fig)
    return save_path


# ─── Latency benchmark ────────────────────────────────────────────────────────
def benchmark_latency(
    models: Dict[str, Any],
    X_sample: np.ndarray,
    n_repeats: int = 200,
) -> pd.DataFrame:
    """Time single-sample inference for each model.

    Returns a DataFrame with columns [model, mean_ms, std_ms].
    X_sample shape: (1, 18) or (n, 18) — uses first row only.
    """
    x1 = X_sample[:1]
    rows = []
    for name, model in models.items():
        times = []
        for _ in range(n_repeats):
            t0 = time.perf_counter()
            predict(model, x1)
            times.append((time.perf_counter() - t0) * 1000)
        rows.append({
            "Model":    name,
            "Mean (ms)": f"{np.mean(times):.4f}",
            "Std (ms)":  f"{np.std(times):.4f}",
        })
    return pd.DataFrame(rows)


def plot_dnn_training_curves(
    per_seed_meta: List[Dict],
    save_path: Path | None = None,
) -> Path:
    """Val-RMSE vs epoch for each seed of the best DNN architecture.

    per_seed_meta is the list of meta dicts from train_multi_seed, each
    containing 'val_history' (list of per-epoch val RMSE), 'seed', 'hidden',
    'dropout', and 'lr'.
    """
    if save_path is None:
        save_path = EVAL_FIG_DIR / "dnn_training_curves.png"

    fig, ax = plt.subplots(figsize=(7, 4))
    colors = plt.cm.tab10.colors
    for meta, color in zip(per_seed_meta, colors):
        history = meta["val_history"]
        label   = f"seed={meta['seed']}  lr={meta['lr']:.0e}"
        ax.plot(range(1, len(history) + 1), history,
                color=color, lw=1.5, label=label)
        # mark the best epoch
        best_ep = int(np.argmin(history))
        ax.scatter(best_ep + 1, history[best_ep], color=color, s=40, zorder=5)

    arch   = per_seed_meta[0]["hidden"]
    drop   = per_seed_meta[0]["dropout"]
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Validation RMSE (z-score)")
    ax.set_title(
        f"DNN training curves — best arch {list(arch)}, dropout={drop}\n"
        f"Dot = early-stop checkpoint"
    )
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(_ensure(save_path))
    plt.close(fig)
    return save_path


def save_latency_table(df: pd.DataFrame, path: Path) -> Path:
    """Write latency DataFrame as a LaTeX booktabs table."""
    _ensure(path)
    lines = [
        r"\begin{tabular}{lrr}", r"\toprule",
        r"Model & Mean (ms) & Std (ms) \\ \midrule",
    ]
    for _, row in df.iterrows():
        lines.append(f'{row["Model"]} & {row["Mean (ms)"]} & {row["Std (ms)"]} \\\\')
    lines += [r"\bottomrule", r"\end{tabular}"]
    path.write_text("\n".join(lines))
    return path
