"""Evaluation: metrics tables, figures, latency benchmark.

Produces (all regenerated by ``make eval``):

  results/tables/
    test_metrics.tex              R^2, RMSE per (model, target) on test
    heldout_rae2822.tex           same on the unseen-geometry slice
    mach_binned_rmse.tex          RMSE per Mach regime
    latency.tex                   mean/std single-sample inference time

  results/figures/
    parity_<model>.png            predicted vs true scatter
    residuals_by_mach_<model>.png bar plot per Mach bin
    cm_vs_alpha_M<mach>.png       Cm(alpha) curves, CFD vs all models
    feature_importance.png        from XGBoost + RF
    learning_curves.png           RMSE vs training set size
"""
# TODO Phase 7
